### PR TITLE
Add all typehints

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by leoloso** [comment]
Hi @szepeviktor this work needs to be done in this component, but also in the other 124 making up plugin GraphQL API for WordPress.

So I'm using only the repo for the plugin to track this development, and none of the individual 125 ones.

These 3 tasks must be done (possibly at the same time, to be more effective) on every component:

- Complete migration of code to PSR-4: GraphQLAPI/graphql-api-for-wp/issues/18
- Upgrade PHPStan to level 8 for all required packages: GraphQLAPI/graphql-api-for-wp/issues/52
- Add Psalm, and generics through docblocks: GraphQLAPI/graphql-api-for-wp/issues/54

Then, the whole everything will be dealt with: PHPStan/CS/PHPUnit all working. Until then all components will have the build failing. I'm OK with this situation, because there's no way around it (only 24hs a day, and I need to sleep every now and then too)

All components are listed down [here](https://github.com/GraphQLAPI/graphql-api/blob/master/dev-helpers/scripts/clone-all-dependencies-from-github.sh)

So, if you don't mind, I'll close this issue here

**Comment by leoloso** [comment]
Sorry @szepeviktor my mistake! I thought this was an issue, not a PR!

**Comment by leoloso** [comment]
I'm happy with your changes, I got totally confused. Don't delete it! However, `function_to_add` is not a `callable`, it's a `string`, exactly same signature as the hooks in WordPress, so I'd need to review your code

**Comment by leoloso** [comment]
Just be aware: there are 125 components where I need to add the typehints. I want you to be aware of the magnitude of the task ahead. But since you've worked on this one, we can merge your changes, once they've been fixed

**Comment by leoloso** [comment]
Actually, it's a `callable`, not a `string`. I'm speaking nonsense today, I need a nap

**Comment by leoloso** [comment]
Please reopen the PR so I can merge it :)

**Comment by szepeviktor** [comment]
I've deleted my branch.
You need to check out this PR locally and cherry-pick 9ba0bc34bec372dce73a63d447c5dc9549ff2166 
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally

**Comment by leoloso** [comment]
Ok, I'll do that. Sorry about my confusion!

**Comment by leoloso** [comment]
Done. Now I go take a nap to get my brain working again 🤣

**Pull request closed without merging**
